/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v2/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Server version */
        get: operations["getVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/plugins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The plugin catalog
         * @description Every plugin installed on this server. `errors` lists manifests that
         *     failed to load and is populated for workspace admins only.
         */
        get: operations["listPlugins"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/plugin-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List plugin runs, newest first
         * @description Keyset pagination on `(created_at, id)`. Pass the previous page's
         *     `next_cursor` as `cursor` to continue; `next_cursor` is `null` on the
         *     last page. Cursors are opaque. Runs created while paging never shift or
         *     repeat entries of later pages: they only appear at the top of a fresh
         *     first page.
         */
        get: operations["listPluginRuns"];
        put?: never;
        /**
         * Queue a plugin run
         * @description Requires the `editor` role or higher.
         */
        post: operations["createPluginRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/plugin-runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One plugin run */
        get: operations["getPluginRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/plugin-runs/{id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The records a run produced */
        get: operations["listPluginRunResults"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/plugin-runs/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a pending or running plugin run
         * @description Requires the `editor` role or higher.
         */
        post: operations["cancelPluginRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/plugin-secrets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the workspace's plugin secrets (metadata only)
         * @description Requires the `admin` role (the owner counts), reads included. Values
         *     are write-only and never returned.
         */
        get: operations["listPluginSecrets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/plugin-secrets/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Create or rotate a workspace plugin secret
         * @description Requires the `admin` role. The name must be declared by an installed
         *     plugin. 201 when created, 200 when rotated.
         */
        put: operations["putPluginSecret"];
        post?: never;
        /**
         * Delete a workspace plugin secret
         * @description Requires the `admin` role.
         */
        delete: operations["deletePluginSecret"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live workspace events (server-sent events)
         * @description A `text/event-stream`. The server sends `retry: 3000`, then unnamed
         *     `data:` messages (so `EventSource.onmessage` receives them), each the
         *     JSON of a `ProgressEvent`, and `: heartbeat` comments to keep the
         *     connection open. Query parameters exist because EventSource cannot send
         *     headers.
         */
        get: operations["streamEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @description Human-readable reason, FastAPI style. */
            detail: string;
        };
        Version: {
            version: string;
            /** @description The Go toolchain version the server was built with. */
            go: string;
        };
        /** @description A JSON Schema (the subset the run form understands). */
        JsonSchemaObject: {
            [key: string]: unknown;
        };
        PluginInfo: {
            name: string;
            display_name: string;
            /** @description provider, scraper, signal, destination, function or tool. */
            kind: string;
            /** @description declarative, wasm or process. */
            runtime: string;
            version: string;
            author: string;
            license: string;
            description: string;
            tags: string[];
            /** @description "plugin" for a manifest v2 plugin, "connector" for a v1 connector loaded as a provider. */
            source: string;
            /** @description "trusted", "unsigned" or another verification outcome. */
            signature: string;
            /** @description Hosts the plugin may reach. */
            network: string[];
            secrets: string[];
            browser: boolean;
            /** @description JSON Schema of the run inputs (type object), or null. */
            inputs: components["schemas"]["JsonSchemaObject"] | null;
            /** @description An entity name (string) or a JSON Schema. */
            outputs: unknown;
            /** @description False when this server cannot execute the plugin yet. */
            runnable: boolean;
            unrunnable_reason?: string;
        };
        PluginLoadError: {
            path: string;
            error: string;
        };
        PluginCatalog: {
            plugins: components["schemas"]["PluginInfo"][];
            /** @description Load failures; empty unless the caller is an admin. */
            errors: components["schemas"]["PluginLoadError"][];
        };
        /** @enum {string} */
        PluginRunStatus: "pending" | "running" | "completed" | "failed" | "cancelled";
        /** @description Run statistics. Keys appear as the run progresses. */
        PluginRunStats: {
            records?: number;
            pages?: number;
            cost_usd?: number;
            duration_ms?: number;
            stopped?: string;
            provider_error?: string;
        } & {
            [key: string]: unknown;
        };
        PluginRun: {
            /** Format: uuid */
            id: string;
            plugin: string;
            plugin_version: string | null;
            status: components["schemas"]["PluginRunStatus"];
            inputs: {
                [key: string]: unknown;
            };
            job_id: number | null;
            created_by: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            started_at: string | null;
            /** Format: date-time */
            completed_at: string | null;
            error: string | null;
            stats: components["schemas"]["PluginRunStats"];
        };
        PluginRunPage: {
            runs: components["schemas"]["PluginRun"][];
            /** @description Pass as `cursor` for the next page; null on the last page. */
            next_cursor: string | null;
        };
        CreatePluginRunRequest: {
            /** @description The `name` of an installed plugin. */
            plugin: string;
            /** @description Validated against the plugin's input schema. */
            inputs?: {
                [key: string]: unknown;
            };
        };
        PluginResult: {
            index: number;
            /** @description The record the plugin produced (any JSON value; normally an object). */
            data: unknown;
            /** @description Where the record came from (source URL, selectors, hashes); shape depends on the plugin runtime. */
            evidence: unknown;
        };
        PluginResultPage: {
            results: components["schemas"]["PluginResult"][];
            total: number;
            offset: number;
            limit: number;
        };
        /** @description Metadata of a stored secret. The value is never returned. */
        PluginSecretMeta: {
            name: string;
            /** @description Installed plugins that declare this secret. */
            plugins: string[];
            version: number;
            /** Format: date-time */
            created_at: string;
            created_by: string | null;
            /** Format: date-time */
            updated_at: string;
            updated_by: string | null;
        };
        PluginSecretDeclared: {
            name: string;
            plugins: string[];
            /** @description A workspace secret with this name is stored. */
            configured: boolean;
        };
        PluginSecretList: {
            secrets: components["schemas"]["PluginSecretMeta"][];
            declared: components["schemas"]["PluginSecretDeclared"][];
            encryption: {
                /** @description Secret encryption is configured on this server. */
                available: boolean;
            };
        };
        PluginSecretValue: {
            /** @description The secret value. Surrounding whitespace is trimmed. */
            value: string;
        };
        /** @description One workspace event on the SSE stream. */
        ProgressEvent: {
            workspace_id: string;
            /** @description Event name, for example `plugin_run_queued` or `plugin_run_cancelled`. */
            event: string;
            /** @description Event payload; shape depends on `event`. */
            data?: unknown;
            /** @description The payload exceeded the NOTIFY limit and was dropped; refetch the resource. */
            truncated?: boolean;
            /** Format: date-time */
            at: string;
        };
    };
    responses: {
        /** @description Missing, invalid or expired token. */
        Unauthorized: {
            headers: {
                "WWW-Authenticate"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not a member of the workspace, SSO is required, or the role is too low. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No such run in this workspace. */
        RunNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unexpected server error. */
        ServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description Workspace authorization (FastAPI) or this server's database is
         *     unavailable. 503 with `Retry-After` means requests are being shed on
         *     purpose (circuit open or too many authorization calls in flight).
         */
        Unavailable: {
            headers: {
                "Retry-After"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description A plugin run id (UUID). Any other value is a 404. */
        RunId: string;
        /** @description The secret name, as declared in a plugin manifest. */
        SecretName: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Version information. No authorization needed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Version"];
                };
            };
        };
    };
    listPlugins: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The catalog. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginCatalog"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            502: components["responses"]["Unavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
    listPluginRuns: {
        parameters: {
            query?: {
                /** @description Page size, 1-200 (values outside the range are clamped). */
                limit?: number;
                /** @description The `next_cursor` of the previous page. */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of runs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginRunPage"];
                };
            };
            /** @description The cursor is not one this server issued. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["ServerError"];
            502: components["responses"]["Unavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
    createPluginRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePluginRunRequest"];
            };
        };
        responses: {
            /** @description The run was queued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginRun"];
                };
            };
            /** @description The body is not valid JSON, or has unknown fields. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description The plugin is not installed. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The inputs do not satisfy the plugin's input schema. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["ServerError"];
            502: components["responses"]["Unavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
    getPluginRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A plugin run id (UUID). Any other value is a 404. */
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The run. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginRun"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["RunNotFound"];
            500: components["responses"]["ServerError"];
            502: components["responses"]["Unavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
    listPluginRunResults: {
        parameters: {
            query?: {
                /** @description Page size, 1-1000 (clamped). */
                limit?: number;
                /** @description Records to skip. */
                offset?: number;
            };
            header?: never;
            path: {
                /** @description A plugin run id (UUID). Any other value is a 404. */
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of results, ordered by record index. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginResultPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["RunNotFound"];
            500: components["responses"]["ServerError"];
            502: components["responses"]["Unavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
    cancelPluginRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A plugin run id (UUID). Any other value is a 404. */
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The cancelled run. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginRun"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["RunNotFound"];
            /** @description The run already finished. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["ServerError"];
            502: components["responses"]["Unavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
    listPluginSecrets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stored secrets, and the secrets installed plugins declare. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginSecretList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["ServerError"];
            502: components["responses"]["Unavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
    putPluginSecret: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The secret name, as declared in a plugin manifest. */
                name: components["parameters"]["SecretName"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PluginSecretValue"];
            };
        };
        responses: {
            /** @description The secret was rotated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginSecretMeta"];
                };
            };
            /** @description The secret was created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginSecretMeta"];
                };
            };
            /** @description The body is not a JSON object with a value field. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Undeclared name, or an empty, oversized or non-UTF-8 value. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["ServerError"];
            502: components["responses"]["Unavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
    deletePluginSecret: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The secret name, as declared in a plugin manifest. */
                name: components["parameters"]["SecretName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description No such secret in this workspace. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Invalid secret name. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["ServerError"];
            502: components["responses"]["Unavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
    streamEvents: {
        parameters: {
            query?: {
                /** @description Bearer token, when the Authorization header cannot be set. */
                token?: string;
                /** @description Workspace, when X-Workspace-Id cannot be set. */
                workspace_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The event stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            502: components["responses"]["Unavailable"];
            503: components["responses"]["Unavailable"];
        };
    };
}
